OppoCamera: Use ContextWrapper from AOSP framework instead of coloros
I think this was a left over derp as rest of the whole code uses the ContextWrapper class from AOSP framework.

Fixes:
07-23 22:21:08.002  5901  7491 E ContextNative: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/color/inner/content/ContextWrapper;
07-23 22:21:08.002  5901  7491 E WindowManagerNative: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/color/inner/view/WindowManagerWrapper;

Signed-off-by: Dakkshesh <dakkshesh5@gmail.com>